apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: betterops
  labels:
    app: producer
    app.kubernetes.io/part-of: betterops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: sarthakyadav783/betterops-producer:e5c9736f9d6e99cf1aa85e90da9e1bf5593833ca
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: betterops-secrets
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: betterops-secrets
                  key: REDIS_URL
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: "500m"
              memory: 512Mi
